config/routes.rb
Tt::Application.routes.draw do
  devise_for :users

  resources :notes do
  
	collection do
		 get :autocomplete_tag_name
		 get :search_by_desc
		  get :search_by_tag
		   get :get_all_notes
		   get :search_tags 
		   get :list_users
	  end
  end

 root :to => "notes#index"

end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :description, :source_url
  acts_as_taggable_on :tags
   validates :description, :presence => true
  
  
#  Relation  
   belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
#  relations 

	has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	before_filter :authenticate_user!
  
  def index
    @note = Note.new
     @tags = Note.tag_counts_on(:tags).order("name asc")
  end

def get_all_notes
    @notes = current_user.notes :include => [:tags] 
  		render :json => notes_with_tags 
end

  def show
    @note = Note.find(params[:id])
  end

  def new
    @note = Note.new
  end

  def create
    @note = current_user.notes.new(params[:note])
    @note.tag_list = params["tag_list"]
    if @note.save
      redirect_to @note, :notice => "Successfully created note."
    else
      render :action => 'new'
    end
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    if @note.update_attributes(params[:note])
    @note.tag_list = params[:tag_list]
    @note.save
      redirect_to @note, :notice  => "Successfully updated note."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to notes_url, :notice => "Successfully destroyed note."
  end
  
  def search_by_desc
  		 @notes = current_user.notes.where("description like ? ", "%#{params[:q]}%").includes(:tags) 
		 @notes = current_user.notes :include => [:tags]   if params[:q] == ""
  		 render :json => notes_with_tags
  end
  
  
   def search_by_tag
  		 @notes = current_user.notes.tagged_with([params[:q]], :any => true).includes(:tags)  
		 @notes = current_user.notes.all :include => [:tags]  if params[:q] == ""
  		 render :json => notes_with_tags
  end
  
  
  def search_tags 
  		 @tags = current_user.notes.tag_counts_on(:tags).order("name asc").where("name like '#{params[:q]}%'")
  		 render :json => @tags
  end
  
  def list_users
  	@users = User.all
  end
  
  private
  
  def notes_with_tags
  		@notes.collect do  |note|
	    {:description => note.description, :id => note.id, :tags => note.tags.collect(&:name)}
	    end
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

def title(title)
"<h1>#{title}</h1>"
end

end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Note Factory" %></title>
    
    <%= include_stylesheets :common, :twitter_bootstrap, :media => 'all' %>
	<%= include_javascripts :common, :twitter_bootstrap %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <!--<body style="background-color: white;background:url(/images/body_back.jpg)	"> -->
    <body style="background-color: white;background:url(/images/cardboard_small.png)	"> 
<div ><h1 style="color:white"> 
Note Cloud
</h1></div>  
<img style="position:fixed;top:-4px;left:160px" src="http://icons.iconarchive.com/icons/wwalczyszyn/iwindows/48/Sticky-Notes-icon.png" />
  <div class="topbar"> 
  
      <div class="fill"> 
        <div class="container"> 
            <ul class ="nav" style="float:right;"> 
             
              <% if user_signed_in? %>
               <li>
    		<a href="#" >Signed in as <%= current_user.email %>. Not you? </a>
     </li>
     <li>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    </li>
  <% else %>
  <li>
    <%= link_to "Sign up", new_user_registration_path  if params[:controller] != "devise/registrations"%> 
    </li>
    <li>
    <%= link_to "Sign in", new_user_session_path if params[:controller] != "devise/sessions"%>
    </li>
  <% end %>
            </ul> 
        </div> 
      </div> 
    </div> 
  <div id="user_nav">
</div>
  
    <div id="container" style="background: #F0F0F0 url(/images/grey_bg.jpg);border-radius: 15px;border-color: white;">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
<!-- User Voice-->
<script type="text/javascript">
  var uvOptions = {};
  (function() {
    var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
    uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/R8dbMDbnSfV90tXIUh1nA.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
  })();
</script>


<!-- Google Analytics-->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29027859-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>


  </body>
</html>

app/views/notes/_form.html.erb
<div class="new_edit_form">
<%= form_for @note, :class=>"form-horizontal" do |f| %>
   <fieldset>
  <%= f.error_messages %>
 <div class="control-group">
   <label class="control-label" for="input01">Description : </label>
    <div class="controls">
    <%= f.text_area :description, :size => "50x4", :placeholder => "Decription"	 %>
    </div>
    </br>
     <div class="control-group">
     <label class="control-label" for="input01">Source Url : </label>
      <div class="controls">
    <%= f.text_field :source_url, :placeholder => "Source url" %>
    </div>
 </div>
  </br>
<div class="control-group">
     <label class="control-label" for="input01">Tags : </label>
      <div class="controls">
      <%= text_field_tag :tag_list,"", :value => @note.tags.join(",") %>
    </div>
 </div>
  </br>
<div class="control-group">
 <label class="control-label" for="input01"> </label>
<div class="controls"  style = "text-align:left">
  <%= f.submit :class=>"btn btn-primary"%></div>
  </div>
     </fieldset>
<% end %>
</div>

<style>
.new_edit_form{

background-color: whiteSmoke;
display: block;
-webkit-border-radius: 3px;
border: 1px solid rgba(0, 0, 0, 0.15);

}
div .control-label {
font-family: Monaco, Andale Mono, Courier New, monospace;
}
</style>

app/views/notes/_header_part.html.erb
<table width="100%">
  <tr><td><h2>Note Cloud</h2></td>
    <td>
      <input autocomplete="off" name="desc" id="search_by_note" class="search span6" class="textbox" placeholder="search by note" tabindex="1" type="text" style="font-size:20px;height:30px; ">
    </td>
    <td>
      <input autocomplete="off" name="tag" id="search_by_tag" class="search span6" class="textbox" placeholder="search by Tag" tabindex="1" type="text" maxlength="140" size="58" value="" style="font-size:20px;height:30px; ">
    </td>
    <td align="right">
<%#= link_to image_tag("new_note.png"), "#new", :id => "new_note", :title => "Add note" %>
      <a href='notes/new' class="label">Create New</a>
    </td>
    <td>
    <a href="#" class="label" id="show_tags">Show Tags</a>
    </td>
     <td>
   <a href="#show_all" class="label" id="show_all">Show all</a>
    </td>
    </tr>
</table>

app/views/notes/_tag_cloud.html.erb
<p>
<input type="text" placeholder="Search Tags" class="search" id="search_tags" />
</p>
<div class="tag_cloud">
<% @tags.each do |tag| %>
  <%= link_to tag.name, "#", :class => 'tag' %>
<% end %>
</div>

app/views/notes/_users_hint.html.erb
<div class="hint pills"> 
  <p style="font-size: 45px;" class=" active">
	  <a href="#" >1</a>Take Note
	  <a href="#" >2</a>Tag it &nbsp;
	  <a href="#" >3</a>Save it &nbsp;
	  <a href="#" >4</a>Search and Find
  </p>
</div>

app/views/notes/ackup.erb
  <!--<%# for note in @notes %>
     <li class="note">
       <a href="<%#= note_path(note) %>">
         <h2><%#= truncate(note.description, :length => 10) %></h2>
         <p><%#= truncate(note.description, :length => 70) %></p>
         <h4 class="tags"><%#= note.tag_list[0, 3]%></h4>
         <div class="note_tag">
     <p style="top: -24px;position: fixed;"><%#= note.tag_list[0, 3]%></p>
 </div>
       </a>
     </li>
<%# end %>
  -->
  
  
  <form style="margin-top: 15px">
  <p>
<textarea name="note" class="span5" rows="4" style="font-size:16px" placeholder="NOTE" >
</textarea>
  </p>
  <p>
<input type="text" class="span5" name="url" style="height:30px;font-size:16px" placeholder="URL" />
  </p>
  <p>
    <input type="text" class="span5" name="tags" placeholder="TAGS" style="height:30px;font-size:16px"/>
  </p>

  <p><button class="save_note btn large primary">Note it</button></p>
</form>







newNote = Backbone.View.extend({
    events: {
        "submit form":          "save"
    },
    element : '#new-note',
    initialize: function(){
        this.render();
    },

    render : function(){
        $(this.element).html(JST.new_note());
    // $('#note_cloud').html(this.el);
    },

    save : function() {
        var note =this.$('[name=note]').val();
        var url =this.$('[name=url]').val();
        var tag_list =this.$('[name=tags]').val();
        alert(url);
        var note = new Note({'note' : {'description' : note, 'source_url' : url}, 'tags' : tag_list })
    }

});

app/views/notes/edit.html.erb
<ul class="breadcrumb">
  <li>
    <a href="/">Home</a> <span class="divider">/</span>
  </li>
  <li >
<a href="/notes/<%= @note.id %>"><%= @note.description.truncate(20)%></a> <span class="divider">/</span>
  </li>
  <li class="active">
Edit Note
  </li>
</ul>

<%= render 'form' %>

app/views/notes/index.html.erb
	
<%= include_stylesheets :note_cloud, :media => 'all' %>
<%= include_javascripts :note_cloud %>
<% content_for :title, "Tag Cloud" %>


<link  href="http://fonts.googleapis.com/css?family=Reenie+Beanie:regular" rel="stylesheet" type="text/css"> 
<link  href="http://fonts.googleapis.com/css?family=Ropa+Sans:regular" rel="stylesheet" type="text/css">

<%= render :partial => "header_part" %>
<ul id="note_cloud"></ul>

<%= render :partial => "users_hint" %>


<div id="new-note" style="width:300px;padding-left:50px;-moz-border-radius:15px 0px 0px 15px;border-radius: 15px 0px 0px 15px; background: none repeat scroll 0 0 rgba(0, 0, 0, 0.5);position:fixed;right:0px;top:100px ;border-color: white;">
</div>

<div id="tag_holder" >
	<p>
<input type="text" placeholder="Search Tags" class="search" id="search_tags" />

</p>
<div class="tag_cloud">

</div>
</div>

<div id="floating_buttons">
</div>

app/views/notes/list_users.html.erb
<% @users.each do |user| %>
	<%= user.email %> <%= user.notes.count %>
<% end %>

app/views/notes/new.html.erb
<ul class="breadcrumb">
  <li>
    <a href="/">Home</a> <span class="divider">/</span>
  </li>
  <li class="active">
New Note
  </li>
</ul>

<%= render 'form' %>

app/views/notes/show.html.erb
<ul class="breadcrumb">
  <li>
    <a href="/">Home</a> <span class="divider">/</span>
  </li>
  <li class="active">
   <%= @note.description.truncate(20) %>
  </li>
</ul>
<pre >
 <p> <strong>Desc : </strong><%= @note.description %></p>
 <p> <strong>Source Url:</strong> <a href="<%= @note.source_url %>"><%= @note.source_url %> </a></p>
    <p> <strong>Tags :</strong>   <%= @note.tags.join(",") %>    </p>
      <p> <strong>Created and Updated on :</strong> <%= @note.created_at.strftime("%d-%m-%Y") %>   &   <%= @note.updated_at.strftime("%d-%m-%Y") %>  </p>
</pre>
<div class="btn-group">
<%= link_to   "Edit", edit_note_path(@note), :class => "btn" %> 
<%= link_to "Destroy", @note, :confirm => 'Are you sure?', :method => :delete, :class => "btn"  %>
        </div>